### ISSUE TITLE
подключить сторонние библиотеки в виде модулей

### ISSUE THREAD

**Issue by sergeymakoveev** [tionix99/mapApp#1]
```
jquery-3.3.1.min
jquery-ui.min
react.production.min v16.7.0
react-dom.production.min v16.7.0
```
Библиотеки должны подключаться в коде приложения как модули (import), их код должен собираться вебпаком в общий бандл приложения.

Чтобы не тратить время на настройку webpack рекомендую воспользоваться [create-react-app](https://facebook.github.io/create-react-app/)

**Comment by tionix99** [comment]
Здравствуйте. 
А я их специально выводил из бандла как внешние, для чистоты бандла так сказать. 
Ок введу через import.

**Comment by tionix99** [comment]
Приложение доработано. Теперь указанные библиотеки установлены как пакеты dependencies и подключаются в коде как модули через import.
С уважением Алексей.
