### ISSUE TITLE
migrate to create-react-app

### ISSUE THREAD

**Issue by sergeymakoveev** [tionix99/mapApp#2]
Чтобы не отвлекаться на конфигурировании webpack перенесите код вашего приложения  под управление [create-react-app](https://facebook.github.io/create-react-app)

Обратите внимание на то, как в компонентах подключаются стили - разбейте файл стилей на отдельные файлы, которые будут подключаться в каждом из ваших реакт-компонент

В результате миграции мы должны избавиться от каталога `public`, файлов index*.html, webpack.*.js

**Comment by tionix99** [comment]
Хорошо, интересно будет посмотреть что получится))).

**Comment by tionix99** [comment]
Перенесенная на create-react-app версия расположена в ветке migrate_to_reactapp. 
Я не сообразил по какому принципу можно разбить css так, чтобы прикрепить свой стиль каждому компоненту - DistanceInfo не использует никаких уникальных стилей вообще, а  ButtonControl использует только общий для всего приложения стиль индикации включения "ON". Также по сути общим является класс .str используемый как CoordPanel, так и в PlacemarkLIst. Исходя из этого чтобы не плодить сущности стили подключены к двум файлам:
к index.js  подключены: 
index.css - стиль body, элементов, и настройки контейнеров, и 
jquery-ui.min.css - нужный для работы app-container.resizable().
к CoordPanel.jsx подключен:
CoordPanel.css - стили элементов внутри компонента CoordPanel.

**Comment by sergeymakoveev** [comment]
> В результате миграции мы должны избавиться от каталога `public`, файлов index*.html, webpack.*.js

Остались проблемы:
* мы не избавились от  каталога `public`, файлов index*.html
* `npm start` не стартует приложение

**Comment by tionix99** [comment]
Очень странно, я проверил - все нормально работает, а что пишет консоль когда приложение не стартует? 

Согласно присланным Вами рекомендациям https://facebook.github.io/create-react-app/ -  
приложение разворачивалось командой 

npx create-react-app <Имя приложения>

и файл package.json а также скрипты запуска в нем
"start": "react-scripts start",
    "build": "react-scripts build",

были созданы автоматически - create-react-app наверняка виднее какие зависимости подтягивать для обеспечения работоспособности собственного приложения - я лишь добавил react и jquery. При установке через npm_i.bat все те же самые зависимости нужные для работы подтягивает react-scripts, и npm run start npm run build также работают нормально. 

Сам create-react-app, который устанавливается глобально насколько я понимаю лишь конфигурирует папку приложения и не привязан собственно к нему, т.е. не влияет на работу приложения.
Возможно (это лишь предположение), что если ОС не Windows, то команды прописанные в скриптах package.json должны быть иными. 
Больше идей нет.

Вообще по команде npm start (npm run start) через react-scripts должен запускаться девсервер который кстати первым делом проверяет наличие public/index.html и вылетает при их отстутсвии - т.е. папка public, и файлы index*.html явлются неотъемлемой частью приложения create-react-app и создаются при его инициализации - я не знаю как можно от них избавиться.
